#ifndef TCPConstants_h
#define TCPConstants_h

uint PACKET_HEADER_LENGTH = 8;
uint MAX_PACKET_PAYLOAD_LENGTH = 1024;
uint MAX_PACKET_LENGTH = PACKET_HEADER_LENGTH + MAX_PACKET_PAYLOAD_LENGTH;

uint MAX_SEQUENCE_NUMBER = 30720;
uint INIT_CONGESTION_SIZE = 1024;
uint INIT_SLOW_START_THRESH = 30720;
uint RTT_VAL= 500;

#endif